
const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
const SET_STATUS_LIST = "SET_STATUS_LIST";
const SET_WISH_LIST = "SET_WISH_LIST";
const SORT = "SORT";
const FILTER = "FILTER";


export { GET_PRODUCTS_REQUEST, GET_PRODUCTS_SUCCESS, SET_STATUS_LIST, SET_WISH_LIST, GET_PRODUCTS_FAILURE, SORT, FILTER }