const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILED = "LOGIN_FAILED";
const LOGOUT_REQUEST = "LOGOUT_REQUEST";
const SIGNUP_REQUEST = "REGISTER_USER";
const SIGNUP_SUCCESS = "REGISTER_SUCCESS";
const SIGNUP_FAILED = "REGISTER_FAILED";

export { LOGIN_REQUEST, LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT_REQUEST, SIGNUP_REQUEST, SIGNUP_SUCCESS, SIGNUP_FAILED }